### ISSUE TITLE
Añadir Topic de cursada

### ISSUE THREAD

**Issue by juli-rivero** [mjkloeckner/CB100#1]
Buenas, estoy trabajando con una página que es muy parecida a FIUBA-Repos, solo que tambien lo podes clasificar por cursos ademas que por materias.

Veo que trabajaste con la cátedra Schmidt, si querés le podes agregar el id del curso asi apareces

En el apartado de [Algoritmos y estructuras de datos](https://juli-rivero.github.io/FIUBA-Share/#/algoritmos-y-estructuras-de-datos/) estan los cursos, entras al curso de Schmidt en el cual trabajaste y le copias el topic. Si lo pegas en el repo y refrescas la página vas a poder ver tu repo

> [!TIP]
> Si agregas los filtros y les copias los topics de estos vas a aparecer aun con los filtros :1st_place_medal: 

Esos topics son los ids que los obtuve del SIU Guaraní - oferta de comisiones, asi que todo oficial :+1:  (excepto por los filtros de actividades que ahí sí me los inventé yo)

Es algo nueva, pero con el tiempo se va a ir llenando de repositorios :100:

**Comment by mjkloeckner** [comment]
Buenas, ahí lo agregué y ya apareció

Como recomendación te puedo sugerir cambiar el id del curso por el nombre de la cátedra/profesor a cargo (Schmidt, en este caso) ya que si bien tiene diferentes horarios por lo general son los mismos contenidos y trabajos prácticos

La sugerencia viene por que es mas intuitivo y práctico agregar el nombre de cátedra que el id del curso, además que también queda mejor el repositorio en github con el nombre que con el id

Saludos, y suerte con la pagina 👍

**Comment by juli-rivero** [comment]
Es una muy buena sugerencia, bien justificada, la verdad lo tengo que pensar y consultar. Abrí un nuevo issue para eso https://github.com/juli-rivero/FIUBA-Share/issues/1
